blank_issues_enabled: false
contact_links:
  - name: Questions / Support
    url: https://github.com/thesorekill/NetworkNick/discussions
    about: Ask questions or get help here (recommended over issues)
